import layout from './layout';

export default {
  borderWidth: 1,
  borderRadius: 4,
  default: {
    borderColor: 'gray.400',
    label: 'gray.200',
    backgroundColor: layout.backgroundColor,
    color: 'gray.200',
    supportingText: 'gray.300',
    icon: 'gray.500',
  },
  focus: {
    borderColor: 'primary.200',
    label: 'primary.200',
    backgroundColor: layout.backgroundColor,
    color: 'white',
    supportingText: 'gray.300',
    icon: 'gray.300',
  },
  valid: {
    borderColor: 'gray.100',
    label: 'gray.100',
    backgroundColor: layout.backgroundColor,
    color: 'white',
    supportingText: 'gray.300',
    icon: 'gray.500',
  },
  invalid: {
    borderColor: 'error.400',
    label: 'error.400',
    backgroundColor: layout.backgroundColor,
    color: 'white',
    supportingText: 'error.400',
    icon: 'error.400',
  },
  disabled: {
    borderColor: 'gray.600',
    label: 'gray.400',
    backgroundColor: layout.backgroundColor,
    color: 'gray.400',
    supportingText: 'gray.400',
    icon: 'gray.500',
  },
  autocompleteDropdown: {
    backgroundColor: 'gray.700',
    backgroundColorSelected: 'gray.600',
    dividerColor: 'gray.400',
    borderWidth: 0,
    borderRadius: 4,
    borderColor: 'gray.500',
    color: 'white',
    fontSize: 't1',
    px: 2,
    py: 1,
    borderBottomWidth: 1,
    borderBottomColor: 'gray.500',
  },
};
